 URL : "https://github.com/UV-CDAT/uvcdat/issues/2176" TITLE : opendap with cdms2 BODY : uvcdat wonâ€™t open opendap addresses generated by a thredds server not esgf - there is a certificate issue with the computer with grads. for example: https://esgf.nccs.nasa.gov/thredds/dodsc/create-ip/reanalysis/nasa-gmao/geos-5/merra2/mon/atmos/tas/tas_amon_reanalysis_merra2_201501-201512.nc using uvcdat 2.10: python 2.7.13 | packaged by conda-forge | default, may 2 2017, 12:48:11 gcc 4.8.2 20140120 red hat 4.8.2-15 on linux2 type help , copyright , credits or license for more information. >>> import cdms2 >>> f=cdms2.open 'https://esgf-data.jpl.nasa.gov/thredds/dodsc/esg_dataroot/obs4mips/observations/atmos/tanobs/mon/grid/nasa-jpl/airs/v20110608/tanobs_airs_l3_retstd-v5_200209-201105.nc' traceback most recent call last : file <stdin> , line 1, in <module> file /home/potter/anaconda2/envs/2.10/lib/python2.7/site-packages/cdms2/dataset.py , line 399, in opendataset raise schemenotsupported scheme typeerror: 'str' object is not callable