 URL : "https://github.com/doomedraven/VirusTotalApi/issues/19" TITLE : error still persist. BODY : vikram@vikram:~/virustotalapi/vt$ python vt.py -ur google.com virustotal.com traceback most recent call last : file vt.py , line 3203, in <module> main file vt.py , line 3130, in main vt.url_scan_and_report options file vt.py , line 1725, in url_scan_and_report print ' searching for url s report: \t{url}'.format url=url_upload.replace ', ', ' \t' attributeerror: 'list' object has no attribute 'replace'