 URL : "https://github.com/automl/auto-sklearn/issues/386" TITLE : typeerror when refit BODY : file /usr/local/lib/python3.5/dist-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/estimators.py , line 50, in refit return self._automl.refit x, y file /usr/local/lib/python3.5/dist-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/estimators.py , line 50, in refit return self._automl.refit x, y file /usr/local/lib/python3.5/dist-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/automl.py , line 497, in refit model.fit x.copy , y.copy file /usr/local/lib/python3.5/dist-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/pipeline/base.py , line 89, in fit self.fit_estimator x, y, fit_params file /usr/local/lib/python3.5/dist-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/pipeline/base.py , line 104, in fit_estimator self.steps -1 -1 .fit x, y, fit_params file /usr/local/lib/python3.5/dist-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/pipeline/components/base.py , line 379, in fit return self.choice.fit x, y, kwargs file /usr/local/lib/python3.5/dist-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/pipeline/components/classification/gradient_boosting.py , line 36, in fit refit=true file /usr/local/lib/python3.5/dist-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/pipeline/components/classification/gradient_boosting.py , line 68, in iterative_fit self.max_leaf_nodes = int self.max_leaf_nodes typeerror: int argument must be a string, a bytes-like object or a number, not 'nonetype'