 URL : "https://github.com/jupyterlab/jupyterlab-google-drive/issues/37" TITLE : can't run in jupyterhub BODY : hi, trying this on our local jupyterhub server using dockerspawner doesn't seem to work, it just shows the googledrive logo without any sign in button. the container logs show no errors: i 2017-07-19 10:57:06.622 xxxxxxxxx extension:38 jupyterlab alpha preview extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab jupyterlab v0.25.2 known labextensions: app dir: /opt/conda/share/jupyter/lab @jupyterlab/google-drive enabled ok i also updated the api key according to https://github.com/jupyterlab/jupyterlab-google-drive/issues/7 issuecomment-306992372. is there a way to get more info to debug this?