 URL : "https://github.com/yisonPylkita/cityblocks/issues/2" TITLE : handle application close BODY : exiting application by clicking close button 'x', results in error thread 'main' panicked at 'called result::unwrap on an err value: ioerror error { repr: os { code: -1073283066, message: os error -1073283066 formatmessagew returned error 317 } } ', src\libcore\result.rs:859 note: run with rust_backtrace=1 for a backtrace. error: process didn't exit successfully: target\debug\cityblocks.exe exit code: 101