 URL : "https://github.com/li-sky/QQthreads/issues/1" TITLE : the no attribute problem BODY : traceback most recent call last : file /home/skyli/.local/lib/python2.7/site-packages/qqbot/qqbotcls.py , line 99, in _call func args, kwargs file /home/skyli/.qqbot-tmp/plugins/bot.py , line 23, in onqqmessage dict2 str dict2_index = contact 8: typeerror: 'group' object has no attribute '__getitem__'